version: '2'
services:
  api:
    build: ./api-server/
    ports:
      - "3000:3000"
    depends_on:
      - "msg"
  msg:
    build: ./msg-server/
    network_mode: "host"
    depends_on:
      - "mq"
      - "redis"
    command: ["./wait-for-it.sh", "mq:5672", "-t", "10", "--", "npm", "start"]
  redis:
    image: redis
  mq:
    image: "rabbitmq:3"
    hostname: "msg-mq"
    ports:
      - "5672:5672"